{{--
    Per-station Liquidsoap script. Rendered by LiquidsoapSupervisor when a
    station is created/updated; written to /var/gocast/liq/{slug}.liq on the
    host; mounted into the station's Liquidsoap container at /station.liq.

    Variables passed in:
      $station         — App\Models\Station
      $icecastPassword — string (from config('services.icecast.source_password'))
      $internalApiKey  — string (matches Laravel's `services.internal_api_key`,
                                 sent in X-Internal-Key header on now-playing pushes)
      $icecastHost     — string \
      $icecastPort     — int     \  Addresses as seen FROM INSIDE this container,
      $apiUrl          — string   > not from wherever Laravel runs. Defaults are
      $rtspHost        — string  /  the compose service names; see the block in
      $rtspPort        — int    /   config/liquidsoap.php for the native-host
                                    overrides.
      $harborPort      — int    (harbor HTTP control surface, /status + /healthz)
      $blankMax        — float  (seconds of silence before the live source is
                                 marked unavailable; 0 disables dead-air strip)
      $blankThreshold  — float  (dBFS below which audio counts as silence)
      $jinglesEnabled  — bool   (initial state of the jingle switch)
      $jingleInterval  — float  (minimum seconds between two jingles)
      $jingleByTracks  — bool   (space jingles by track count, not by time)
      $jingleEveryTracks — int  (tracks between jingles in that mode)

      Free-tier watermark — platform-owned, never the owner's to change:
      $watermarkSupported — bool  (build it into the graph at all)
      $watermarkEnabled   — bool  (initial state, from the owner's PLAN)
      $watermarkInterval  — float (seconds between watermarks)
      $watermarkDuck      — float (portion of station audio KEPT, 0..1)
      $watermarkFade      — float (ramp down/up seconds)
      $watermarkContainerDir — string (mount point of the clip directory)

    IMPORTANT: every string we emit into Liquidsoap source goes through
    json_encode (via @json). Blade's default {{ }} HTML-escapes, which is
    the wrong escaping for a Liquidsoap script — it would turn `&` into
    `&amp;` and corrupt URLs/passwords. json_encode also handles backslashes,
    double quotes, control characters, and unicode the way Liquidsoap's
    lexer expects, so values containing `$ \ "` (e.g. an icecast password
    with shell metacharacters) can't break the script.

    The station slug is the one exception: it's produced by Str::slug() so
    it's already restricted to `[a-z0-9-]` and safe to interpolate raw via
    `{{ }}` after we strip surrounding quotes.
--}}
# === GoCast station: {{ $station->slug }} ===
# Auto-generated by LiquidsoapSupervisor — DO NOT EDIT BY HAND.
# Regenerated on station change; container restart applies it.

settings.log.stdout.set(true)
# Level 2 = warning. Level 3 (info) emits one line per RTSP retry while no
# broadcaster is publishing — that's once per ~2 seconds, all day. Bump back
# up while debugging an audio chain issue.
settings.log.level.set(2)

# Telnet control surface — Laravel sends commands here for skip/reload.
# Bound to 0.0.0.0 inside the container; only reachable on the gocast
# Docker network so Laravel can connect by container name.
settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("0.0.0.0")
settings.server.telnet.port.set(1234)

# === Lifecycle reporting ===
#
# The container is the only thing that knows it came up. Laravel's `docker run`
# returns when the container is CREATED, not when audio flows — so without this
# push, a station that dies at boot and one that is still building its audio
# graph look identical from outside for as long as anyone cares to poll.
#
# These events are a fast path, not a source of truth: a script that fails to
# parse dies before any of them can fire, which is why Laravel also verifies the
# container after start and keeps polling /status. Losing an event must never
# strand a station.
ice_up = ref(false)

def notify(event) =
  ignore(http.post(
    {!! json_encode("{$apiUrl}/api/internal/station-event") !!},
    data=json.stringify({ slug = {!! json_encode($station->slug) !!}, event = event }),
    headers=[
      ("Content-Type", "application/json"),
      ("Accept", "application/json"),
      ("X-Internal-Key", {!! json_encode($internalApiKey) !!})
    ],
    timeout=5.
  ))
end

on_start(fun () -> notify("boot"))
on_shutdown(fun () -> notify("shutdown"))

# Validates a broadcaster before harbor accepts their connection.
#
# The password is the short-lived, station-scoped token Laravel minted for the
# studio; the same token the WHIP path used to put in the URL query. Laravel
# verifies its MAC, expiry and station binding and answers 200 or 4xx. Anything
# other than a clean 200 is a refusal — a network blip must not become an open
# door, so we fail closed.
#
# Blocking by design: harbor calls this on the connection thread and one
# request per connection attempt is cheap.
# log.severe, not log.important: important is level 3 and this script runs at
# level 2, so a refusal would be invisible in `docker logs` — leaving an
# operator staring at "the stream server closed the connection" with nothing
# to go on. Every path through here says why, at a level that is actually
# printed.
def harbor_auth(login) =
  try
    response = http.post(
      {!! json_encode("{$apiUrl}/api/internal/harbor-auth") !!},
      data=json.stringify({
        slug = {!! json_encode($station->slug) !!},
        user = login.user,
        password = login.password,
        address = login.address
      }),
      headers=[
        ("Content-Type", "application/json"),
        ("Accept", "application/json"),
        ("X-Internal-Key", {!! json_encode($internalApiKey) !!})
      ],
      timeout=5.
    )

    if response.status_code == 200 then
      true
    else
      log.severe("harbor: refused #{login.user} from #{login.address} (HTTP #{response.status_code})")
      false
    end
  catch _ do
    # Laravel unreachable — DNS, a dev server bound to loopback, a restart
    # mid-request. Still fail closed, because an API we cannot ask must never
    # become an open door, but name the cause: this is indistinguishable from
    # a bad password from the broadcaster's side.
    log.severe(
      "harbor: cannot reach the auth API at "
      ^ {!! json_encode("{$apiUrl}/api/internal/harbor-auth") !!}
      ^ " — refusing #{login.user}. Is the API reachable from this container?"
    )
    false
  end
end

# === Inputs ===

# Live broadcaster — connects straight into this container over the webcast
# WebSocket protocol (the studio) or the Icecast source protocol (BUTT, Mixxx,
# RocketBroadcaster). Fallible: only present while someone is publishing.
#
# Broadcasters publish here directly over the webcast protocol — a WebSocket
# carrying a JSON hello frame then binary MP3. input.harbor speaks it natively
# alongside the traditional Icecast source protocol, so BUTT, Mixxx and friends
# can connect to the same mount with no extra machinery.
#
# This replaced an input.ffmpeg RTSP pull from MediaMTX. WebRTC needed ICE, and
# ICE needs UDP the broadcaster's network may simply refuse: a VPN with leak
# protection, a firewall that blocks UDP, or symmetric NAT all produced a
# session that negotiated successfully and then never carried a byte. A
# WebSocket reaches anyone who can load the studio page.
#
# `auth` is called per connection attempt and validates the short-lived
# broadcast token Laravel minted for the studio (see harbor_auth below).
#
# buffer() decouples harbor's arrival timing from Liquidsoap's main clock so a
# momentary network hiccup on the broadcaster's side doesn't underrun the
# output. 2s nominal, 10s before samples are dropped.
live_in = input.harbor(
  {!! json_encode($station->slug) !!},
  port={{ $harborInputPort }},
  auth=harbor_auth
)

# on_connect/on_disconnect replace MediaMTX's runOnReady/runOnNotReady hooks:
# they are what tells Laravel to open and close the StreamSession that makes a
# station read as live. Same fast-path caveat as every other event here —
# `stations:reconcile` closes any session a lost notification strands.
#
# Registered as METHODS on the source, not as arguments to input.harbor. The
# argument form still works in 2.4 but logs a deprecation on every boot and is
# slated for removal.
#
# synchronous=false is not optional here: notify() makes an HTTP POST with a
# 5s timeout, and a synchronous callback runs on the streaming thread — a slow
# or hanging API would stall the audio for every listener. Same reasoning as
# the blank.detect callbacks below.
live_in.on_connect(synchronous=false, fun (_) -> notify("live_connected"))
live_in.on_disconnect(synchronous=false, fun () -> notify("live_disconnected"))

live_raw = buffer(buffer=2., max=10., live_in)

@if ($blankMax > 0)
# Dead-air guard. A broadcaster who mutes their mic, sleeps their laptop or
# loses their audio device keeps the RTSP session open — the stream is still
# "there", it's just silent. Without this the fallback below stays locked on
# `live` and every listener hears nothing while AutoDJ sits idle behind it.
#
# blank.strip declares the source unavailable after {{ $blankMax }}s under
# {{ $blankThreshold }} dB, which is exactly the signal fallback needs to
# demote to AutoDJ on its own. It re-promotes as soon as audio returns.
#
# The threshold is deliberately forgiving: a dramatic pause or a quiet intro
# must never knock a real broadcaster off air.
{{-- number_format keeps a literal decimal point in the output: Liquidsoap's
     lexer needs `15.0`, and a bare `{{ $blankMax }}.` would emit `15.5.` for
     any non-integer value, which is a syntax error. --}}
live = blank.strip(
  max_blank={{ number_format($blankMax, 1, '.', '') }},
  threshold={{ number_format($blankThreshold, 1, '.', '') }},
  live_raw
)

# blank.strip demotes silently — the broadcaster whose mic is muted hears
# AutoDJ take over and has no idea why. blank.detect watches the same signal
# without touching the audio, purely so we can tell them.
#
# In 2.4 these callbacks are methods, not constructor arguments; the form the
# published docs show does not compile.
silence_watch = blank.detect(
  max_blank={{ number_format($blankMax, 1, '.', '') }},
  threshold={{ number_format($blankThreshold, 1, '.', '') }},
  live_raw
)
silence_watch.on_blank(synchronous=false, fun () -> notify("live_silent"))
silence_watch.on_noise(synchronous=false, fun () -> notify("live_audio"))
@else
live = live_raw
@endif

@if ($autodjDynamic)
# === AutoDJ rotation — one track at a time, from Laravel ===
#
# WHY THIS IS NOT A PLAYLIST. The obvious shape is `playlist("playlist.m3u")`,
# and it was, until the reload it requires was measured on 2.4.5: after
# `playlist_m3u.reload` the list restarts at index 0. Laravel must send that
# reload after every track add/remove/reorder — so uploading a song sent every
# listener back to song one, a few tracks later (the prefetched requests drain
# first, which is why it looked random). Manual reload and reload_mode="watch"
# behave the same; there is no cursor-preserving reload.
#
# So the running order moved out of Liquidsoap. This asks Laravel for ONE track
# whenever it needs one, which is how AzuraCast and LibreTime both work. There
# is no list in here to reset, and nothing to reload: a track added mid-rotation
# is simply returned when the rotation reaches its position, and the audio is
# never touched. It also means the ordering is a QUERY — which is the only form
# in which rotation rules, dayparting or ad breaks can ever be expressed.
#
# Blocking HTTP is fine here and would not be in a track handler:
# `request.dynamic` resolves requests on its own asynchronous queue (the
# default, synchronous=false), not on the streaming thread.
#
# null() means "nothing to play", and it is a NORMAL answer — a station with an
# empty library is the common case for a live-only broadcaster. It makes this
# source unavailable, and the fallback below demotes to the silence bed exactly
# as an empty m3u used to. The API being unreachable produces the same audio
# outcome, so the two are distinguished in the log rather than in the graph:
# silence because there is nothing to play is not a fault, silence because
# Laravel cannot be reached is.
#
# retry_delay is rendered rather than left at Liquidsoap's 0.1s default: that
# would mean ten requests per second, forever, for every empty station.
def autodj_next() =
  try
    r = http.get(
      {!! json_encode($nextTrackUrl) !!},
      headers=[
        ("Accept", "text/plain"),
        ("X-Internal-Key", {!! json_encode($internalApiKey) !!})
      ],
      timeout=5.
    )

    if r.status_code == 200 then
      uri = string.trim(string_of(r))
      if uri == "" then null else request.create(uri) end
    elsif r.status_code == 204 then
      # No rotation. Expected, and silent on purpose: logging it would print a
      # line every retry_delay seconds for the life of every live-only station.
      null
    else
      log.severe("autodj: next-track answered HTTP #{r.status_code} — rotation stalled")
      null
    end
  catch _ do
    log.severe(
      "autodj: cannot reach the next-track API at "
      ^ {!! json_encode($nextTrackUrl) !!}
      ^ " — rotation stalled. Is the API reachable from this container?"
    )
    null
  end
end

autodj = request.dynamic(
  id = {!! json_encode($liqSource) !!},
  retry_delay = { {{ number_format($autodjRetryDelay, 1, '.', '') }} },
  autodj_next
)

# `playlist` registered a `.skip` telnet command for free; `request.dynamic`
# does not — it offers `.flush_and_skip`, which also throws away the track
# already fetched for the crossfade. StationPowerController sends
# "{{ $liqSource }}.skip", so we register that name ourselves and point it at
# the source's own skip. Verified over telnet: without this the command answers
# "unknown command" and skip-track silently does nothing.
autodj.register_command(
  description = "Skip the current AutoDJ track",
  "skip",
  fun (_) -> begin autodj.skip() ; "Done" end
)
@else
# === AutoDJ rotation — legacy playlist file ===
#
# Reached only with LIQUIDSOAP_AUTODJ_DYNAMIC=false. Kept as the rollback path
# for the dynamic rotation above, on the same principle as the crossfade gate:
# this is the audio path, so a way back should be an env var and a relaunch.
# PlaylistFileWriter still writes playlist.m3u in both modes, so flipping back
# needs nothing else.
#
# Known defect, which is why it is no longer the default: the reload Laravel
# must send after a track change restarts the list at index 0 — verified on
# 2.4.5 for both manual reload and reload_mode="watch".
#
# Reads playlist.m3u, written by PlaylistFileWriter on every track mutation.
# The file sits in the dir mounted as /data/playlists/. `mode = "normal"`
# plays top-to-bottom and loops; `reload_mode = "never"` leaves reloading to
# Laravel's telnet call. Fallible when the m3u is missing or empty, which lets
# fallback() below demote to the silence bed until tracks exist.
#
# Not wrapped in normalize() — it pumps quiet sections loud and crushes louder
# ones, which sounds like the volume is breathing on its own. If we ever need
# cross-track loudness leveling, swap in a proper LUFS limiter.
#
# `on_fail` fires when no track resolves after `max_fail` attempts. It must
# return a list of replacement URIs; we have none, so the empty list lets the
# fallback demote to the bed as it would anyway.
autodj = playlist(
  id = {!! json_encode($liqSource) !!},
  "/data/playlists/playlist.m3u",
  mode = "normal",
  reload_mode = "never",
  on_fail = fun () -> begin
    log(level=2, "playlist: no playable track — falling through to silence")
    ([] : [string])
  end
)
@endif

# === Jingles ===
#
# Station IDs, liners, sweepers — whatever the owner uploaded to the jingle
# list. Read from a SECOND m3u (PlaylistFileWriter writes both on every track
# mutation) rather than being mixed into the rotation, because a jingle is not
# a rotation entry: it must not take its turn in order, must not be reordered
# by the user's drag handles, and must not be crossfaded.
#
# `mode = "randomize"` shuffles within the list, so a station with three IDs
# doesn't play them in a fixed cycle. `reload_mode = "never"` matches the
# rotation: Laravel fires `jingles_m3u.reload` over telnet after any change.
#
# This block is rendered for EVERY station, including the majority that never
# turn jingles on — see the interactive variables below for why. Measured on
# 2.4.5: a station whose jingles.m3u is empty logs three lines about it at boot
# and nothing ever again. `on_fail` does not fire, because nothing pulls from a
# source the fallback never selects.
jingles = playlist(
  id = {!! json_encode($jinglesLiqSource) !!},
  {!! json_encode("/data/playlists/{$jinglesFilename}") !!},
  mode = "randomize",
  reload_mode = "never",
  on_fail = fun () -> begin
    log(level=2, "jingles: no playable jingle — rotation continues uninterrupted")
    ([] : [string])
  end
)

# INTERACTIVE VARIABLES, not literals — and that is the whole point.
#
# Baked in as constants, changing either setting would mean re-rendering this
# script and restarting the container, which drops every listener mid-track.
# Nobody should lose their audience to change how often a station ID plays.
# As interactive variables they are settable at runtime over the same telnet
# socket that already drives playlist reloads:
#
#   var.set {{ $jinglesEnabledVar }} = true
#   var.set {{ $jingleIntervalVar }} = 900.0
#
# LiquidsoapSupervisor::applyJingleSettings() sends exactly those two. The
# values rendered here are the INITIAL state, read from the station row, so a
# container that boots (or reboots) is already correct without anyone having to
# push anything — telnet is the fast path, this is the source of truth.
#
# Verified on 2.4.5: a station booted with jingles off and a 600s interval,
# then switched on at 5s over telnet, played its next jingle at the following
# track boundary with no restart and no gap in the audio.
{{-- Rendered as bare true/false: Liquidsoap has no truthy ints, and @json
     would emit `1`/`0`, which is a type error rather than a wrong value. --}}
jingles_enabled = interactive.bool({!! json_encode($jinglesEnabledVar) !!}, {{ $jinglesEnabled ? 'true' : 'false' }})
jingle_by_tracks = interactive.bool({!! json_encode($jingleByTracksVar) !!}, {{ $jingleByTracks ? 'true' : 'false' }})
jingle_interval = interactive.float({!! json_encode($jingleIntervalVar) !!}, {{ number_format($jingleInterval, 1, '.', '') }})
jingle_every_tracks = interactive.int({!! json_encode($jingleEveryTracksVar) !!}, {{ $jingleEveryTracks }})

# How many rotation tracks have played since the last jingle. Only consulted in
# track mode, but counted always — so switching modes mid-broadcast doesn't
# start from a stale number.
#
# The handlers are registered on the LEAF sources (the two playlists), not on
# anything downstream: a track mark on the fallback would already have been
# through cross(), and we would be counting transitions rather than tracks.
#
# synchronous=true here, against the convention everywhere else in this file.
# The rule that makes the other callbacks asynchronous is that they do I/O —
# an HTTP post on the streaming thread stalls audio for every listener. These
# two do a single integer assignment, and they must be ORDERED with respect to
# the track mark that triggered them: the fallback re-evaluates availability at
# that same boundary, and a counter updated on a separate task can arrive after
# the decision it was supposed to inform.
tracks_since_jingle = ref(0)
autodj.on_track(synchronous=true, fun (_) -> tracks_since_jingle := tracks_since_jingle() + 1)
jingles.on_track(synchronous=true, fun (_) -> tracks_since_jingle := 0)

# THIS is the whole scheduling mechanism, and it is worth understanding
# because it is not obvious from reading it.
#
# There are two ways to space jingles and the owner picks one per station:
#
#   interval mode — "every 30 minutes". Predictable in wall-clock terms, which
#                   is what legal IDs and sponsor reads are specified in, and
#                   independent of how long the station's tracks are.
#   track mode    — "every 5 tracks". Even musical density, which is what the
#                   owner actually hears, at the cost of real-world spacing
#                   that swings with track length.
#
# Rather than two graphs, there is one graph with two gates, and the mode
# neutralises whichever gate it isn't using. That is what keeps the mode itself
# switchable at runtime: a graph that changed shape per mode could only change
# by restarting the container.
#
#   delay() is the TIME gate. It holds a source unavailable for N seconds after
#   each of its own end-of-tracks, reading N as a getter per evaluation — which
#   is why lowering the interval takes effect on the wait already in progress
#   rather than the one after it. In track mode N is 0, so it never blocks.
#
#   jingle_due() is the COUNT gate, and also the on/off switch. In interval
#   mode the count half is vacuously true, so delay() alone decides.
#
# source.available applies the count gate, and it is deliberately NOT
# track_sensitive. That flag was here once and was a bug: it defers evaluation
# of the PREDICATE to an end-of-track of the source it wraps — which is the
# jingle, and the jingle is not playing while music runs. So the count was only
# re-read when a jingle ended, latching a stale "true" and firing a jingle after
# every single track, sometimes two back to back. Observed on a real station,
# with jingle_due() true at counter=1 against a threshold of 3.
#
# The "only switch at a track boundary" guarantee comes from the fallback below,
# which is where it belongs: that flag defers the SWITCH, this one deferred the
# QUESTION. The only thing lost by evaluating continuously is that switching
# jingles off mid-jingle now cuts it short rather than letting it finish — which
# is a fair reading of "off" anyway.
#
# fallback(track_sensitive=true) is what makes the whole thing safe: it only
# reconsiders which source wins AT A TRACK BOUNDARY. A jingle becoming ready
# mid-song changes nothing; the switch happens when the current song ends. That
# is the difference between "a station ID every half hour" and "a station ID
# that chops a song in half every half hour" — and it is why this flag is
# spelled out here rather than left to the default.
#
# Contrast the fallback further down, which is deliberately
# track_sensitive=FALSE: a human broadcaster going live SHOULD interrupt
# instantly rather than wait out a five-minute track.
#
# initial=true so a station does not open with a jingle: the delay starts
# counting from boot, not from the first end-of-track. Track mode gets the same
# protection for free, since the counter starts at zero.
#
# Fallible on both arms, which is correct — an empty jingle list or an empty
# rotation just falls through to the silence bed below.
def jingle_delay() =
  if jingle_by_tracks() then 0.0 else jingle_interval() end
end

def jingle_due() =
  jingles_enabled()
  and (not jingle_by_tracks() or tracks_since_jingle() >= jingle_every_tracks())
end

jingle_arm = source.available(
  delay(initial=true, jingle_delay, jingles),
  jingle_due
)

autodj_rotation = fallback(track_sensitive = true, [jingle_arm, autodj])

# Crossfade AutoDJ track transitions — 2s overlap between consecutive
# playlist tracks. Liquidsoap 2.4+ API: `duration` is the only required
# parameter (the old start_next/fade_in/fade_out signature was removed).
#
# This wraps the AutoDJ rotation alone (rotation + jingles), and deliberately
# NOT the live/AutoDJ fallback below.
# crossfade is a track-boundary operator: it buffers audio and applies a
# fade-out envelope to the outgoing side and a fade-in to the incoming one.
# A live broadcast is one continuous track, so wrapping the fallback meant
# every re-evaluation of it started another 2s gain ramp over live audio.
# Those ramps stacked — "clock.cross: there are currently 551 sources,
# possible source leak" — and listeners heard the level slide down and then
# snap back up. The churn also starved the streaming thread, which then
# logged "Latency is too high: we must catchup 1.22 seconds" and skipped
# samples to recover, adding an audible jump on top of the fades.
#
# Bound to a NEW name rather than rebinding `autodj`: the cross operator
# returns a plain source, which drops the playlist's own methods, and the
# status endpoint must never call methods on it (see the /status handler).
#
# WHY THIS IS GATED, and what to look for if it comes back.
#
# On Liquidsoap 2.4.0 every form of cross() wedged AutoDJ on a track boundary:
# the crossfade() wrapper, a hand-written cross() transition, and the
# cross.smart port below. Output degenerated to a single buffered frame emitted
# forever — a static harmonic spectrum, dead flat for 20s, which listeners hear
# as a stuck-PC buzz. elapsed() climbed past the track length, remaining() froze
# at a constant, decoder End_of_file stopped firing, and NOTHING was logged
# while CPU and memory stayed healthy.
#
# Root cause was upstream, not this script: savonet#4851 attached the
# crossfade's `transition` and `pre_buffer` sources to the passive child clock
# instead of the top-level one, so nothing animated them. Fixed in Liquidsoap
# 2.4.3. The image is pinned to 2.4.5, which also carries savonet#5194 — a
# cross/crossfade crash when source.skip runs from a harbor.http handler, and
# this script serves /status and /healthz over harbor.http.
#
# Detection, since none of it reaches the log: End_of_file should appear once
# per track, and elapsed()+remaining() from /status should equal the track
# duration. If EOF goes quiet while elapsed keeps climbing, it is wedged. Do NOT
# use `request.all` returning two rids as the tell — the playlist legitimately
# prefetches the next track, so two rids is normal on a healthy station.
#
# Recovery is LIQUIDSOAP_CROSSFADE_ENABLED=false plus a relaunch: hard cuts are
# known good, and no code has to change to get there.
@if ($crossfadeEnabled)
# Level-aware transition ported from AzuraCast's `cross.smart`, which is the
# reference implementation for this pipeline. The point is that it does NOT
# always overlap: it compares the loudness of the outgoing and incoming track
# and only fades when the result will not turn to mush, hard cutting otherwise.
# That is what keeps a master limited to 0.0 dBFS — measured on the current
# jazz track — from clipping the encoder while two tracks are summed.
# duration = the cross WINDOW (audio buffered either side of the boundary).
# fade     = the length of the envelopes drawn inside that window, and it must
# be strictly shorter. Book §6.4: "The total duration should always be strictly
# longer than the one of the fades, otherwise the fades will not be complete and
# you will hear abrupt changes in the volume." These were one value for both
# until now, i.e. permanently in exactly that broken case. Laravel clamps the
# fade below the window before rendering.
autodj_cross_duration = {{ number_format($crossfadeDuration, 1, '.', '') }}
autodj_cross_fade = {{ number_format($crossfadeFade, 1, '.', '') }}
autodj_cross_high = {{ number_format($crossfadeHigh, 1, '.', '') }}
autodj_cross_medium = {{ number_format($crossfadeMedium, 1, '.', '') }}
autodj_cross_margin = {{ number_format($crossfadeMargin, 1, '.', '') }}

def autodj_cross_fade_out(s) =
  fade.out(type="sin", duration=autodj_cross_fade, s)
end

def autodj_cross_fade_in(s) =
  fade.in(type="sin", duration=autodj_cross_fade, s)
end

# add() relays metadata from the FIRST available source only, so the incoming
# track is listed first: the other order makes /status announce the track that
# just finished for the whole overlap. normalize=false because add()'s own
# normalization divides by the source count, ducking every transition by 6dB.
def autodj_cross_add(ending, starting) =
  add(normalize=false, [starting, ending])
end

def autodj_cross(a, b) =
  # The fades are built inside each branch, never up front: an unused source
  # still gets created and has to be torn down again.
  #
  # Reading .metadata here also satisfies cross(): it only exposes that field
  # on these records when the script references it, and the type checker needs
  # to see that happen. AzuraCast pokes it with a throwaway `ignore` for
  # exactly this reason — we reference it for real instead.
  if
    # A jingle is never crossfaded. Sliding a produced station ID under the
    # tail of a song is the sound of an accident, and it defeats the point:
    # the ID exists to be heard cleanly. `jingle="true"` is annotated onto
    # every entry in jingles.m3u by PlaylistFileWriter — a station with no
    # jingles never carries it, so this branch is simply never taken there.
    a.metadata["jingle"] == "true" or b.metadata["jingle"] == "true"
  then
    sequence([a.source, b.source])
  elsif
    a.db_level <= autodj_cross_medium
    and b.db_level <= autodj_cross_medium
    and abs(a.db_level - b.db_level) <= autodj_cross_margin
  then
    # Both quiet and close together — safe to fade both ways.
    autodj_cross_add(autodj_cross_fade_out(a.source), autodj_cross_fade_in(b.source))
  elsif
    b.db_level >= a.db_level + autodj_cross_margin
    and a.db_level >= autodj_cross_medium
    and b.db_level <= autodj_cross_high
  then
    # Incoming is much louder — fade the outgoing track out under it.
    autodj_cross_add(autodj_cross_fade_out(a.source), b.source)
  elsif
    a.db_level >= b.db_level + autodj_cross_margin
    and b.db_level >= autodj_cross_medium
    and a.db_level <= autodj_cross_high
  then
    # Outgoing is much louder — fade the incoming track in under it.
    autodj_cross_add(a.source, autodj_cross_fade_in(b.source))
  elsif
    b.db_level >= a.db_level + autodj_cross_margin
    and a.db_level <= autodj_cross_medium
    and b.db_level <= autodj_cross_high
  then
    # Outgoing is already near silence — overlap without fading it further.
    autodj_cross_add(a.source, b.source)
  else
    # Too loud to overlap, or too far apart for one to survive the mix.
    # A hard cut is the honest answer. This is the arm a 0.0 dBFS master
    # takes, which is why the clipping went away.
    sequence([a.source, b.source])
  end
end

autodj_faded = cross(duration=autodj_cross_duration, autodj_cross, autodj_rotation)
@else
# Hard cuts: LIQUIDSOAP_CROSSFADE_ENABLED=false.
autodj_faded = autodj_rotation
@endif

# The limiter is overflow protection, not loudness shaping, and it has no
# track/timing logic that could hang. Masters brick-walled to 0.0 dBFS leave
# the MP3 encoder no headroom even without an overlap. Scoped to the AutoDJ
# arm so the live path is untouched. This is NOT normalize() — the gain is
# static above threshold, so it cannot "breathe" on quiet passages.
autodj_mix = limit(threshold=-1.0, autodj_faded)

# Standby silence — infallible last resort.
bed = mksafe(blank())

# === Audio brain ===
# Priority: live > autodj > bed. track_sensitive=false means a live
# broadcaster connecting mid-AutoDJ-track interrupts immediately rather
# than waiting for the track to end.
#
# mksafe() promises Liquidsoap's type checker that this chain is infallible.
# Required because output operators downstream refuse fallible sources, and
# fallback() is conservatively typed as fallible even when the last element
# (bed = mksafe(blank())) is provably infallible at runtime.
mixed = mksafe(fallback(track_sensitive=false, [live, autodj_mix, bed]))

# Nothing further processes the mix: source switches are hard cuts by design.
# Fading between live and AutoDJ would mean fading live audio, which is the
# bug described above. A broadcaster dropping off air should cut to AutoDJ.
output_source = mixed

# === Free-tier watermark ===
#
# A short platform clip mixed OVER the station every few minutes, ducking
# whatever is playing instead of replacing it. Unlike a jingle this is not the
# owner's content and not the owner's decision: it comes from the plan, there
# is no station column for it, and no API surface can switch it off.
#
# WHY IT IS HERE, BELOW THE FALLBACK, AND NOT UP WITH THE JINGLES.
#
# Free plans have autodj_enabled = false, so a free station has no track
# library — its AutoDJ arm is silence and everything a listener hears is a live
# broadcast. Applied to the AutoDJ arm this would therefore be inaudible, and
# applied anywhere above the live/AutoDJ fallback it would be evaded by the one
# action a free station can take: going live. So it sits after the fallback,
# where it catches everything.
#
# That means putting an operator on the live path, which this file otherwise
# treats as forbidden — see the crossfade notes above. The distinction is that
# cross() is a TRACK-BOUNDARY operator, and a live broadcast is one endless
# track: it re-triggered forever and stacked hundreds of sources. smooth_add
# has no track logic at all; it reads a gain getter and sums. Verified rather
# than assumed: 42 seconds of an endless, mark-free carrier with the watermark
# firing repeatedly produced no source leak, no latency catch-up, and a carrier
# level of exactly -25.5 dB against a predicted 0.15 x -9.03 dB.
#
# `output_source` is deliberately left pointing at the un-watermarked mix. The
# /status endpoint and the now-playing push both read it, and they should keep
# reporting what the STATION is playing — a platform ID is not the station's
# now-playing, and routing it through here would also risk the clip's own
# metadata overwriting a real track title. Only the outputs below take the
# watermarked source.
@if ($watermarkSupported)
# A DIRECTORY, not a filename: Liquidsoap plays whatever is in it, so several
# variants rotate at random, and an EMPTY directory just makes this fallible.
# That is the important property — a station must never fail to start because
# the operator has not dropped a clip in yet.
watermark = playlist(
  id = "watermark",
  {!! json_encode($watermarkContainerDir) !!},
  mode = "randomize",
  reload_mode = "never",
  on_fail = fun () -> begin
    log(level=2, "watermark: no clip in {{ $watermarkContainerDir }} — station plays unmarked")
    ([] : [string])
  end
)

# Interactive for the same reason the jingle settings are: an upgrade must
# silence this within seconds, without restarting the container and dropping
# the listeners the owner just paid to keep.
watermark_enabled = interactive.bool({!! json_encode($watermarkEnabledVar) !!}, {{ $watermarkEnabled ? 'true' : 'false' }})
watermark_interval = interactive.float({!! json_encode($watermarkIntervalVar) !!}, {{ number_format($watermarkInterval, 1, '.', '') }})
watermark_duck = interactive.float({!! json_encode($watermarkDuckVar) !!}, {{ number_format($watermarkDuck, 3, '.', '') }})

# Skip it when the station is on air but nobody is broadcasting and there is no
# rotation — i.e. the silence bed. "Powered by GoCast" alone into an otherwise
# silent stream reads as a fault rather than as branding. Same readiness test
# the /status endpoint uses to name the current source, so the two cannot
# disagree about whether anything is playing.
def watermark_due() =
  watermark_enabled() and (live.is_ready() or autodj_mix.is_ready())
end

# Not track_sensitive — same reasoning as the jingle arm above, plus a reason
# of its own: a watermark rides on top rather than replacing a track, so it has
# no boundary to wait for, and on a live stream there are none in any case.
watermark_arm = source.available(
  delay(initial=true, watermark_interval, watermark),
  watermark_due
)

# `p` is the portion of the station's own audio KEPT during the watermark, not
# the amount removed — 0.15 leaves the host at 15%. Liquidsoap's 0.2 default is
# tuned for ducking music; speech under speech needs to go further down.
broadcast_source = smooth_add(
  duration = {{ number_format($watermarkFade, 1, '.', '') }},
  p = watermark_duck,
  normal = output_source,
  special = watermark_arm
)
@else
# Watermarking is switched off for this install (LIQUIDSOAP_WATERMARK_ENABLED).
broadcast_source = output_source
@endif

# We deliberately do NOT run normalize() here. It's a dynamic AGC that
# pumps quiet audio louder and crushes loud audio quieter — the classic
# "breathing" artifact, especially audible on voice with natural pauses.
# If we ever need cross-track leveling, swap in a tasteful LUFS limiter
# (e.g. the loudness_normalization() snippet from the Liquidsoap docs)
# rather than the raw normalize() operator.

# === Control surface: harbor HTTP ===
#
# Liquidsoap knows things Laravel can only infer: what is playing right now,
# how far into it we are, which source won the fallback, and whether the
# audio graph is actually producing sound. Pushing all of that out and hoping
# the receiver was up is how state desyncs; serving it lets Laravel pull the
# truth whenever it needs it — and "container unreachable" becomes an honest
# offline signal instead of a separate flag to keep in sync.
#
# Bound inside the container on {{ $harborPort }}, reachable only over
# gocast-network (same exposure as the telnet port). /status requires the
# shared internal key so a foothold on the docker network can't read station
# state; /healthz is deliberately open — it carries no station data and wants
# to be usable as a container HEALTHCHECK.

# `req` rather than `request`: Liquidsoap's standard library already binds
# `request` at the top level, and shadowing it warns on every boot.
def internal_key_of(req) =
  # Harbor lowercases incoming header names, but don't bet the auth check
  # on that — look for both spellings.
  lower = req.headers["x-internal-key"]
  if lower != "" then lower else req.headers["X-Internal-Key"] end
end

def authorized(req) =
  internal_key_of(req) == {!! json_encode($internalApiKey) !!}
end

# Which source the fallback is currently taking. Derived from readiness in
# priority order — the same order fallback() itself uses — so it can't drift
# from what listeners actually hear.
def current_source() =
  if live.is_ready() then
    "live"
  elsif autodj_mix.is_ready() then
    "autodj"
  else
    "silence"
  end
end

# `response.json` raises on NaN and infinity — JSON cannot represent either —
# and a raised handler answers nothing at all, closing the socket. That turns
# the single most load-bearing endpoint we have into a dead one: Laravel reads
# the failure as "container unreachable" and reports the station as `starting`
# forever, while the container is perfectly healthy.
#
# It is not a corner case. `remaining()` is infinite whenever the source has no
# end — which is every station playing the silence bed, i.e. any station whose
# playlist is empty and whose broadcaster is offline.
#
# -1 rather than null: the API layer already maps negative durations to null
# (see StationStatusService::normalize), so this stays a single convention for
# "unknown" instead of introducing a second one.
def finite(x) =
  if float.is_nan(x) or float.is_infinite(x) then -1. else x end
end

harbor.http.register(port={{ $harborPort }}, method="GET", "/status", fun (req, response) ->
  if not authorized(req) then
    response.status_code(403)
    response.data("forbidden")
  else
    m = output_source.last_metadata()
    meta = null.defined(m) ? null.get(m) : ([] : [(string * string)])
    response.json(
      {
        slug = {!! json_encode($station->slug) !!},
        ready = output_source.is_ready(),
        # Whether the audio graph produces frames is NOT the same question as
        # whether anyone can hear it: if Icecast rejects the source (bad
        # password, Icecast down) the graph is perfectly ready and the mount
        # does not exist. Reporting both is what lets Laravel tell "on air"
        # from "playing to nobody".
        icecast = ice_up(),
        source = current_source(),
        title = meta["title"],
        artist = meta["artist"],
        elapsed = finite(output_source.elapsed()),
        # playlist_length and up_next deliberately do NOT appear here.
        # They used to call autodj.length()/remaining_files() — methods on the
        # very source cross() is fast-forwarding. Book §6.4: that fast-forward
        # "is only possible when only one operator is using the source,
        # otherwise we will run into synchronization issues." This endpoint is
        # polled every couple of seconds, so it was a second operator on a
        # crossfaded source on every single poll. Laravel serves both fields
        # from its own tracks table instead, where they are exact.
        remaining = finite(output_source.remaining())
      }
    )
  end
)

# /healthz is the container's Docker HEALTHCHECK, so its STATUS CODE is the
# contract, not its body: 200 when this container is doing its job, 503 when it
# is not. Docker's probe greps the status line (the image has no curl, wget or
# nc — it uses bash's /dev/tcp), and `stations:reconcile` treats a container
# that reports unhealthy as drift and recreates it.
#
# It answers exactly one question: IS THIS CONTAINER'S AUDIO GRAPH WORKING —
# because recreating the container is the only remedy on offer, and that is the
# only failure a recreate can fix.
#
# The Icecast connection is deliberately NOT part of the verdict, even though a
# station that cannot reach Icecast is inaudible. If it were, an Icecast outage
# would mark every station on the box unhealthy at once and the reconciler would
# recreate the entire fleet — repeatedly, and to no effect, since restarting a
# station does not fix Icecast. Liquidsoap already retries the connection itself
# (see on_error below), and the disconnection is surfaced to operators through
# /status as the `degraded` state instead. Health drives automation; degraded
# drives attention.
#
# Deliberately unauthenticated: it carries no station data, and a healthcheck
# that needs a secret is a healthcheck that breaks when the secret rotates.
harbor.http.register(port={{ $harborPort }}, method="GET", "/healthz", fun (_, response) ->
  begin
    if not output_source.is_ready() then response.status_code(503) end
    response.json({ ready = output_source.is_ready(), icecast = ice_up(), source = current_source() })
  end
)

# === Now-playing push ===
#
# Fires every time the metadata at the top of the chain changes — track
# advance in the playlist, broadcaster connecting/disconnecting, etc.
# We POST the payload to Laravel which caches it in Redis; the listener
# API surfaces this so the player UI shows "now playing" without waiting
# for the in-stream ICY frame.
#
# In LS 2.4 on_metadata is a method on the source object (not a top-level
# function). `synchronous=false` runs the callback on a separate task so an
# HTTP hiccup can't block the audio thread.
# X-Internal-Key matches the api container's INTERNAL_API_KEY env var.
#
# Jingles are skipped. A station ID is not "now playing" in the sense the
# player UI means it — swapping the listener's display to "GoCast FM Jingle"
# for eight seconds and then back is worse than leaving the last real track
# up, which is what skipping the push achieves (Laravel caches the last
# payload; no push means no change).
#
# Note this does NOT suppress the in-stream ICY title, which output.icecast
# derives from the same metadata: a listener watching their player's own
# StreamTitle readout still sees the jingle go by. Suppressing that would mean
# rewriting the metadata on the source itself, which would also blank it out
# of /status — and /status should keep reporting what is genuinely on air.
def push_now_playing(m) =
  if m["jingle"] == "true" then
    ()
  else
    payload = json.stringify(
      {
        slug = {!! json_encode($station->slug) !!},
        title = m["title"],
        artist = m["artist"]
      }
    )
    ignore(http.post(
      {!! json_encode("{$apiUrl}/api/internal/now-playing") !!},
      data=payload,
      headers=[
        ("Content-Type", "application/json"),
        ("Accept", "application/json"),
        ("X-Internal-Key", {!! json_encode($internalApiKey) !!})
      ],
      timeout=5.
    ))
  end
end

output_source.on_metadata(synchronous=false, push_now_playing)

# === Outputs ===

# Icecast — listener URL: https://icecast.gocast.fm{{ $station->icecast_mount }}
icecast_out = output.icecast(
  %mp3(bitrate=128, samplerate=44100),
  host = {!! json_encode($icecastHost) !!},
  port = {{ $icecastPort }},
  password = {!! json_encode($icecastPassword) !!},
  mount = {!! json_encode($station->icecast_mount) !!},
  name = {!! json_encode($station->name) !!},
  description = {!! json_encode($station->description ?? '') !!},
  genre = {!! json_encode($station->genre ?? '') !!},
  # Send StreamTitle bytes as UTF-8 — without this, Liquidsoap defaults to
  # ISO-8859-1 and silently rewrites every non-Latin character (Arabic,
  # CJK, accented letters in some forms) to "*" before the metadata even
  # leaves the server.
  encoding = "UTF-8",
  broadcast_source
)

# The only place that knows whether listeners can actually hear this station.
# `ice_up` feeds /status (so Laravel can distinguish "ready" from "audible")
# and /healthz (so a station that silently loses its mount is restarted rather
# than sitting there producing audio for nobody).
#
# on_error must call restart_in or the output gives up permanently; 5s is long
# enough not to hammer a restarting Icecast and short enough that a blip costs
# listeners seconds, not minutes.
icecast_out.on_connect(synchronous=false, fun () -> begin
  ice_up := true
  notify("icecast_connected")
end)

icecast_out.on_disconnect(synchronous=false, fun () -> begin
  ice_up := false
  notify("icecast_disconnected")
end)

icecast_out.on_error(synchronous=false, fun (~restart_in, _) -> begin
  ice_up := false
  restart_in(5.)
  notify("icecast_error")
end)

# HLS — listener URL: https://stream.gocast.fm/{{ $station->slug }}/playlist.m3u8
# Caddy serves /var/gocast/hls/{slug}/ (mounted here at /data/hls) from the
# ingest vhost — see the @hls matcher in api/Caddyfile.
#
# The web player streams from Icecast, not from here; HLS exists for clients
# that can't hold a long-lived MP3 socket (iOS lock screen, native apps, CDN
# pull). Single bitrate for v1; add a 64k variant later for cellular ABR.
#
# `persist_at` lets a restart resume the existing HLS stream instead of
# starting a fresh one. Station edits re-render the .liq and restart the
# container, and without this every restart resets the media sequence — an
# HLS client mid-stream sees a discontinuity and usually stalls or reloads.
# Liquidsoap writes its segment state here on shutdown and reads it on boot.
#
# `segments_overhead` keeps segments around past the playlist window so a
# client that fell behind still finds the segment it asked for rather than
# a 404.
output.file.hls(
  "/data/hls",
  segment_duration = 2.,
  segments = 5,
  segments_overhead = 5,
  persist_at = "/data/hls/state.json",
  playlist = "playlist.m3u8",
  [("aac", %ffmpeg(format="mpegts", %audio(codec="aac", b="128k")))],
  broadcast_source
)
